"""
"""

@_(req=[
    'import plistlib',
],argspec={
    'args': [
        {'name': 'outfile',
         'default': '/tmp/ex1-Info.plist',
         },
    ],
})
def gen1(args):
    """
    """
    outfile = args.outfile

    out = {
        # Basic bundle metadata normally generated by Xcode;
        #   kept here so this plist can also document the file-type registration.
        "CFBundleDevelopmentRegion": "$(DEVELOPMENT_LANGUAGE)",
        
        "CFBundleExecutable"            : "$(EXECUTABLE_NAME)",
        "CFBundleIdentifier"            : "$(PRODUCT_BUNDLE_IDENTIFIER)",
        "CFBundleInfoDictionaryVersion" : "6.0",
        "CFBundleName"                  : "$(PRODUCT_NAME)",
        "CFBundlePackageType"           : "$(PRODUCT_BUNDLE_PACKAGE_TYPE)",
        "CFBundleShortVersionString"    : "$(MARKETING_VERSION)",
        "CFBundleVersion"               : "$(CURRENT_PROJECT_VERSION)",
        "NSHumanReadableCopyright"      : "",
        "NSMainStoryboardFile"          : "Main",
        "NSPrincipalClass"              : "NSApplication",

        # Declare the app as a viewer for files whose content type is the custom safetensors UTType below.
        "CFBundleDocumentTypes": [
            
            {
                "CFBundleTypeName":  "safetensors file",
                "CFBundleTypeRole":  "Viewer",
                "LSHandlerRank":     "Owner",
        
                # Legacy extension mapping helps older Launch Services paths recognize .safetensors even before Spotlight has refreshed metadata.
                
                "CFBundleTypeExtensions": [
                    "safetensors",
                ],
                
                "LSItemContentTypes": [
                    "io.util.safetensors.file",
                ],
            },
        ],

        # Export a Uniform Type Identifier so Launch Services and QuickLook
        #    can associate .safetensors paths with this app.
        "UTExportedTypeDeclarations": [

            {
                # This app owns the safetensors UTI, which lets
                #    Finder match .safetensors files to the viewer and QuickLook extension.
                "UTTypeConformsTo": [
                    "public.data",
                ],
                
                "UTTypeDescription":      "safetensors file",
                "UTTypeIdentifier":       "io.util.safetensors.file",
                "UTTypeTagSpecification": {
                    "public.filename-extension": [
                        "safetensors",
                    ]
                },
            }
        ],

    }

    with open(outfile,'wb') as fp:
        plistlib.dump(
            out,
            fp,
            sort_keys = False,
        )
    print("wrote:",outfile)
    




@_(req=[
    'import plistlib',
],argspec={
    'args': [
        {'name': 'outfile',
         'default': '/tmp/ex2-Info.plist',
         },
    ],
})
def gen2(args):
    """
    """
    outfile = args.outfile

    out = {

        #Mirror the containing app's UTI declaration so the appex
        #  advertises the same .safetensors type during plugin discovery.
	"UTExportedTypeDeclarations" : [
            
            {
                "UTTypeConformsTo" : ["public.data"],
		"UTTypeDescription" : 	"safetensors file", 
		"UTTypeIdentifier" : 	"io.util.safetensors.file", 
		"UTTypeTagSpecification" : {
		    "public.filename-extension" : ["safetensors"],
                },

            }
        ],

	"NSExtension": {

	    "NSExtensionAttributes" : {
                # Keep this as a view-based QuickLook preview implemented by PreviewViewController.
		"QLIsDataBasedPreview" : False,
                
                # Advertise the safetensors UTType exported by the containing app.
		"QLSupportedContentTypes" : ["io.util.safetensors.file"],
                
                # This preview reads files directly and does not vend previews for CoreSpotlight searchable items yet.
		"QLSupportsSearchableItems" : False,
            },
            
            # Register this appex with QuickLook's preview extension point.
	    "NSExtensionPointIdentifier" : "com.apple.quicklook.preview", 
        
            # Use the XIB-backed preview controller that renders the basic header label.
	    "NSExtensionPrincipalClass" : "$(PRODUCT_MODULE_NAME).PreviewViewController", 
        }
    }

    with open(outfile,'wb') as fp:
        plistlib.dump(out,fp,sort_keys = False)
    print("wrote:",outfile)
